"""
MHRS SaaS — Custom Data Encryption Module
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Implements a two-layer encryption scheme for sensitive patient data:

  Layer 1 — Custom Character Substitution (configurable char map)
             Applied to plaintext before cryptographic encryption.
             Adds domain-specific obfuscation that custom per-tenant
             char maps can be rotated without re-encrypting.

  Layer 2 — Fernet Symmetric Encryption (AES-128-CBC + HMAC-SHA256)
             Industry-standard authenticated encryption.
             Key stored in ENCRYPTION_KEY env variable.

Public API:
  encrypt_field(text: str) -> str   — produce ciphertext string (base64)
  decrypt_field(token: str) -> str  — recover original plaintext
"""
import base64
import hashlib
from cryptography.fernet import Fernet, InvalidToken
from app.config import get_settings

settings = get_settings()

# ══════════════════════════════════════════════════════════════════════════════
# LAYER 1 — Custom Character Substitution Map
# ══════════════════════════════════════════════════════════════════════════════
# The CHAR_MAP is built deterministically from the CHAR_SUBSTITUTION_SEED.
# You can override it entirely with a tenant-specific map for white-labeling.
#
# Default substitution covers alphanumeric + common chars.
# To customize: change CHAR_SUBSTITUTION_SEED in .env or provide CUSTOM_CHAR_MAP.

_DEFAULT_CHAR_MAP: dict[str, str] = {
    # Vowels → symbols
    "a": "@", "A": "4",
    "e": "3", "E": "&",
    "i": "!", "I": "1",
    "o": "0", "O": "ø",
    "u": "µ", "U": "ü",
    # Common consonants
    "s": "$", "S": "§",
    "t": "+", "T": "†",
    "n": "η", "N": "Ñ",
    "m": "μ", "M": "Μ",
    "g": "9", "G": "Ğ",
    "h": "#", "H": "Η",
    "l": "λ", "L": "Λ",
    "r": "ρ", "R": "Ρ",
    "b": "β", "B": "Β",
    "c": "ç", "C": "Ç",
    "d": "δ", "D": "Δ",
    "f": "φ", "F": "Φ",
    "k": "κ", "K": "Κ",
    "p": "π", "P": "Π",
    "v": "ν", "V": "ν",
    "x": "χ", "X": "Χ",
    "y": "γ", "Y": "Υ",
    "z": "ζ", "Z": "Ζ",
    # Digits → shifted
    "0": "⁰", "1": "¹", "2": "²", "3": "³", "4": "⁴",
    "5": "⁵", "6": "⁶", "7": "⁷", "8": "⁸", "9": "⁹",
}

# Reverse map: used for decryption Layer 1 reversal
_REVERSE_CHAR_MAP: dict[str, str] = {v: k for k, v in _DEFAULT_CHAR_MAP.items()}


def _build_seed_char_map(seed: str) -> tuple[dict[str, str], dict[str, str]]:
    """
    Generates a deterministic substitution map from a seed string.
    The seed scrambles the order of the default map values.
    This allows per-tenant char maps without changing the implementation.
    """
    chars = list(_DEFAULT_CHAR_MAP.keys())
    replacements = list(_DEFAULT_CHAR_MAP.values())

    # Use SHA256 of seed as deterministic shuffle key
    seed_hash = hashlib.sha256(seed.encode()).hexdigest()
    seed_int = int(seed_hash, 16)

    # Fisher-Yates shuffle using seed
    reps = replacements[:]
    for i in range(len(reps) - 1, 0, -1):
        j = seed_int % (i + 1)
        reps[i], reps[j] = reps[j], reps[i]
        seed_int //= (i + 1)

    fwd = dict(zip(chars, reps))
    rev = {v: k for k, v in fwd.items()}
    return fwd, rev


# Build maps from configured seed
_CHAR_MAP, _REV_MAP = _build_seed_char_map(settings.char_substitution_seed)


def _substitute(text: str, char_map: dict[str, str]) -> str:
    """Apply character substitution. Unknown chars pass through unchanged."""
    result = []
    for ch in text:
        result.append(char_map.get(ch, ch))
    return "".join(result)


# ══════════════════════════════════════════════════════════════════════════════
# LAYER 2 — Fernet Symmetric Encryption
# ══════════════════════════════════════════════════════════════════════════════

def _get_fernet() -> Fernet:
    """
    Returns a Fernet instance using the ENCRYPTION_KEY from settings.
    The key must be 32 url-safe base64 bytes (Fernet standard).
    If the key is not a valid Fernet key, it is SHA-256 derived and encoded.
    """
    key_raw = settings.encryption_key.encode()
    try:
        # Try direct use (if key was generated by Fernet.generate_key())
        return Fernet(key_raw)
    except Exception:
        # Derive a valid 32-byte key from whatever string is provided
        derived = base64.urlsafe_b64encode(
            hashlib.sha256(key_raw).digest()
        )
        return Fernet(derived)


# ══════════════════════════════════════════════════════════════════════════════
# Public API
# ══════════════════════════════════════════════════════════════════════════════

def encrypt_field(text: str) -> str:
    """
    Encrypt a sensitive text field for database storage.

    Flow:
      plaintext → Layer 1 substitution → Layer 2 Fernet → base64 ciphertext

    Args:
        text: The plaintext string to encrypt.

    Returns:
        A URL-safe base64-encoded ciphertext string (safe for VARCHAR columns).

    Example:
        >>> encrypted = encrypt_field("12345678901")  # TC No
        >>> len(encrypted) > 0
        True
    """
    if not text:
        return text
    # Layer 1: custom substitution
    substituted = _substitute(text, _CHAR_MAP)
    # Layer 2: Fernet encryption
    fernet = _get_fernet()
    ciphertext_bytes = fernet.encrypt(substituted.encode("utf-8"))
    return ciphertext_bytes.decode("utf-8")


def decrypt_field(token: str) -> str:
    """
    Decrypt a field encrypted by encrypt_field().

    Flow:
      ciphertext → Layer 2 Fernet decrypt → Layer 1 reverse substitution → plaintext

    Args:
        token: The encrypted string as returned by encrypt_field().

    Returns:
        The original plaintext string.

    Raises:
        ValueError: If decryption fails (key mismatch or tampered data).

    Example:
        >>> decrypt_field(encrypt_field("hello")) == "hello"
        True
    """
    if not token:
        return token
    try:
        fernet = _get_fernet()
        decrypted_bytes = fernet.decrypt(token.encode("utf-8"))
        substituted = decrypted_bytes.decode("utf-8")
        # Reverse Layer 1 substitution
        return _substitute(substituted, _REV_MAP)
    except InvalidToken as exc:
        raise ValueError("Decryption failed: invalid token or wrong key.") from exc


def encrypt_medical_record(record: dict) -> dict:
    """
    Encrypts a dictionary of medical record fields in-place.
    Fields listed in SENSITIVE_FIELDS will be encrypted.

    Args:
        record: dict of field_name → value

    Returns:
        New dict with sensitive fields encrypted.
    """
    SENSITIVE_FIELDS = {"notes", "complaint", "diagnosis", "prescription", "tc_no"}
    encrypted = {}
    for key, value in record.items():
        if key in SENSITIVE_FIELDS and isinstance(value, str):
            encrypted[key] = encrypt_field(value)
        else:
            encrypted[key] = value
    return encrypted
